version: 2
updates:
  - package-ecosystem: nuget
    directory: '/generators/server/templates/dotnetcore/src'
    schedule:
      interval: daily
      time: '11:00'
    open-pull-requests-limit: 10
    target-branch: dependencies   
